sudo: required
services:
  - docker

before_install:
  - cd client
  - docker build -t araxis/react-test -f ./Dockerfile.dev .
  - cd ../

script:
  - docker run araxis/react-test npm test -- --coverage

after_success:
  - cd client
  - docker build -t araxis/multi-client ./client .
  - cd ../

  - cd nginx
  - docker build -t araxis/multi-nginx  ./nginx  .
  - cd ../

  - cd server
  - docker build -t araxis/multi-server ./server .
  - cd ../

  - cd worker
  - docker build -t araxis/multi-worker ./worker .
  - cd ../

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push araxis/multi-client
  - docker push araxis/multi-nginx
  - docker push araxis/multi-server
  - docker push araxis/multi-worker
